fixtures:
  symlinks:
    hugo: "#{source_dir}"
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.14.0'
    remotefile:
      repo: 'https://github.com/lwf/puppet-remote_file.git'
      ref: 'v1.1.3'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
