name: "Spec tests"

on:
  workflow_dispatch:
  pull_request:

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-20.04
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}

    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Setup Spec Test Matrix
      id: get-matrix
      run: |
        MATRIX=$(cat spec_matrix.json |tr "\n" ' '|sed 's/\s\+/ /g')
        echo  "::set-output name=spec_matrix::$MATRIX"

  spec:
    name: "Spec Tests (Puppet: ${{matrix.puppet_version}}, Ruby Ver: ${{matrix.ruby_version}})"
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.spec_matrix != '{}' }}

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.spec_matrix)}}

    env:
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
      - run: |
          echo "SANITIZED_PUPPET_VERSION=$(echo '${{ matrix.puppet_version }}' | sed 's/~> //g')" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby_version}}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: Run Static & Syntax Tests
        run: |
          bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop

      - name: Run parallel_spec tests
        run: |
          bundle exec rake parallel_spec
